name = "hotel-ping-app"
main = "src/worker.js"
compatibility_date = "2026-01-01"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hotel-ping-db"
database_id = "018a4539-a04b-4ada-841d-1962bcde934d"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "hotel-ping-uploads"

[vars]
VAPID_PUBLIC_KEY = "BCaJBvwGIigjmyBzyh3CgYpzpzbbl4rHeTw3hWLRHp1I52D35oKqQsW2k19ZghGh4evavlwqbAzP-CsuJ-xLBkU"
VAPID_SUBJECT = "mailto:admin@hotelping.co.uk"

[triggers]
crons = ["*/5 * * * *"]

[[routes]]
pattern = "hotelping.co.uk"
custom_domain = true

[[routes]]
pattern = "www.hotelping.co.uk"
custom_domain = true
