name = "hotel-ping-app"
main = "src/worker.js"
compatibility_date = "2026-01-01"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hotel-ping-db"
database_id = "018a4539-a04b-4ada-841d-1962bcde934d"

[[d1_databases]]
binding = "NOIR_DB"
database_name = "noir-house-db"
database_id = "e20a018c-4228-4343-856f-9c80bf3cc8dd"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "hotel-ping-uploads"

[ai]
binding = "AI"

[vars]
VAPID_PUBLIC_KEY = "BCaJBvwGIigjmyBzyh3CgYpzpzbbl4rHeTw3hWLRHp1I52D35oKqQsW2k19ZghGh4evavlwqbAzP-CsuJ-xLBkU"
VAPID_SUBJECT = "mailto:admin@hotelping.co.uk"

[triggers]
crons = ["* * * * *"]

[[routes]]
pattern = "app.hotelping.co.uk"
custom_domain = true
